[[language]]
name = "lua"
shebangs = ["lua", "luajit"]
roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml", ".git"]
language-servers = [ "C:\\Users\\AHAH43\\AppData\\Local\\nvim-data\\mason\\packages\\lua-language-server\\bin\\lua-language-server.exe" ]


[[language]]
name = "python"
language-servers = ["ty", "ruff", "jedi", "pyright"]# "pylsp"]

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python", rev = "293fdc02038ee2bf0e2e206711b69c90ac0d413f" }
